In [1]:
import cv2
print(cv2.__version__)

4.4.0


In [2]:
#cv2.startWindowThread()
#cv2.namedWindow('test_image', cv2.WINDOW_NORMAL)
#cv2.namedWindow('Gray image', cv2.WINDOW_NORMAL)
image=cv2.imread('/Users/jon.heffer/python/ss4.png')
image2=cv2.imread('/Users/jon.heffer/python/flira.jpg')
#image=cv2.rotate(image,cv2.ROTATE_90_CLOCKWISE)
#image2=cv2.rotate(image2,cv2.ROTATE_90_CLOCKWISE)
#cv2.imshow('test_image',image)
#gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
#cv2.imshow('Gray image', image2)

#cv2.waitKey(0)
#cv2.destroyAllWindows()

In [3]:
print(image[[0],[0]])

[[28 16 16]]


In [4]:
temp=(142.-20.)*11./210.+32. 
print('temp is ',temp)

temp is  38.39047619047619


In [5]:
#for i in range(1,10):
    #cv2.destroyAllWindows()
    #cv2.waitKey(1)
import numpy as np
import matplotlib.cm as cm
import matplotlib.pyplot as plt
import matplotlib.cbook as cbook
from matplotlib.path import Path
from matplotlib.patches import PathPatch
from scipy.interpolate import interp1d

%matplotlib widget
fig, ax = plt.subplots()
im = ax.imshow(image, interpolation='bilinear', cmap=cm.RdYlGn)

left, bottom, width, height = (200, 200, 50, 80)
rect = plt.Rectangle((left, bottom), width, height,
                     facecolor="white", alpha=0.5)


ax.add_patch(rect)
plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [6]:
colourbar=image[range(430,1260),55]
colourbar=np.flipud(colourbar)
fig, ax = plt.subplots()
plt.plot(colourbar[:,0])
u, indices = np.unique(colourbar[:,0], return_index=True)
maxT=43.
minT=32.
span=maxT-minT

f = interp1d(tuple(np.float32(u)), tuple(np.float32(indices)/np.amax(indices)*span+minT),fill_value="extrapolate")
f(230)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

array(42.62547302)

In [7]:
cap = cv2.VideoCapture('/Users/jon.heffer/python/tests.mp4')
total = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
print('total = ',total)



total =  255


In [8]:
val=np.empty(total,dtype=float)
count=0

left=230
top=410
bottom=450 
right=260

mask=np.zeros((640, 480), dtype=bool)
mask[np.arange(top,bottom)[None,:],np.arange(left,right)[:,None]]=1
mask[np.arange(top+1,bottom-1)[None,:],np.arange(left+1,right-1)[:,None]]=0

np.shape(mask)


(640, 480)

In [9]:
cap.set(2,0.1) 
while(cap.isOpened()):
    ret, frame = cap.read()
    if  not ret: 
        break
        
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    
    sub=gray[np.arange(top,bottom)[None,:],np.arange(left,right)[:,None]]
    
    val[count]=np.mean(sub)
    gray[mask]=255
    cv2.imshow('frame',gray)
    
    
    cv2.waitKey(1) 
    count += 1
cap.release()
cv2.waitKey(0)
np.shape(gray)

(640, 480)

In [10]:
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib.figure import Figure



fig, (ax1, ax2) = plt.subplots(1, 2)
canvas = FigureCanvas(fig)
ax1.imshow(gray)
ax2.plot(f(tuple(val)))

canvas.draw()       # draw the canvas, cache the renderer
image_from_plot = np.frombuffer(fig.canvas.tostring_rgb(), dtype=np.uint8)
image_from_plot = image_from_plot.reshape(fig.canvas.get_width_height()[::-1] + (3,))
plt.show



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

<function matplotlib.pyplot.show(*args, **kw)>

In [ ]:
cv2.imshow('sss',image_from_plot)
cv2.waitKey(0)

In [10]:
fig, ax = plt.subplots()
plt.plot(f(tuple(val)))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [11]:
n1, n2 = np.arange(5), np.arange(5)
n1[None,:]

array([[0, 1, 2, 3, 4]])

In [12]:
range(200,300)

range(200, 300)

In [13]:
np.arange(2,5)

array([2, 3, 4])

In [14]:
np.range(2,4)


AttributeError: module 'numpy' has no attribute 'range'